# Generated by Django 5.2.4 on 2025-07-29 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
