# Generated by Django 5.2.4 on 2025-07-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choose',
            field=models.CharField(choices=[('pots', 'статья'), ('news', 'новость')], default='pots', max_length=4),
        ),
    ]
