# Generated by Django 5.2.4 on 2025-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choose',
            field=models.CharField(choices=[('article', 'статья'), ('news', 'новость')], default='article', max_length=10),
        ),
    ]
