# Generated by Django 5.2.4 on 2025-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choose',
            field=models.CharField(choices=[('article', 'статья'), ('new', 'новость')], default='new', max_length=10),
        ),
    ]
